name: Deploy to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential pandoc

      - name: Build site
        run: make html

      - name: Copy static dir
        run: cp -r static/ target/

      - name: List target dir
        run: ls -R target

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
